package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// writeSingleVPSSetup renders the single-VPS cluster mode (N containers on one
// host) into renderDir, replacing the single-node nats.conf / docker-compose.
// Each container gets its own config: distinct server_name, client/route/http
// ports and a mesh to the sibling containers on the compose network.
func writeSingleVPSSetup(renderDir string, data map[string]any, replicas int, hostName string) error {
	authBlock := natsAuthBlock(data)
	cluster, _ := data["ClusterName"].(string)
	if cluster == "" {
		cluster = "nla"
	}
	// The node's shared server cert must carry the container-name SANs too
	// (generated by gen-certs.sh with GEN_NODES covering nats-0..n-1).
	for i := range replicas {
		var routes []string
		for j := range replicas {
			if j == i {
				continue
			}
			routes = append(routes, fmt.Sprintf("    nats://nats-%d:6222", j))
		}
		conf := fmt.Sprintf(`server_name: %s-%d
listen: 0.0.0.0:%d
http: 127.0.0.1:%d
max_connections: %v
max_payload: 1MB
max_pending: 100MB

tls {
  cert_file: "/certs/server.pem"
  key_file:  "/certs/server.key"
  ca_file:   "/certs/ca.pem"
  timeout: 2
  verify: true
  handshake_first: true
}

jetstream {
  store_dir: /data
  max_memory_store: %v
  max_file_store: %v
  sync_interval: 120s
  key: $JS_KEY
}

cluster {
  name: %s
  listen: 0.0.0.0:%d
  routes: [
%s
  ]
  tls {
    cert_file: "/certs/server.pem"
    key_file:  "/certs/server.key"
    ca_file:   "/certs/ca.pem"
  }
}

%s
`,
			hostName, i, 4222+i, 8222+i,
			data["MaxConnections"],
			data["MaxMemoryStore"], data["MaxFileStore"],
			cluster, 6222+i, strings.Join(routes, "\n"),
			authBlock)
		if err := os.WriteFile(filepath.Join(renderDir, fmt.Sprintf("nats-%d.conf", i)), []byte(conf), 0600); err != nil {
			return err
		}
	}

	// Multi-service compose on a shared bridge network.
	var sb strings.Builder
	sb.WriteString("name: nats-single\nservices:\n")
	for i := range replicas {
		fmt.Fprintf(&sb, `  nats-%d:
    image: nats:2.14-alpine
    restart: unless-stopped
    container_name: nats-%d
    command: ["-c", "/etc/nats/nats-%d.conf"]
    environment:
      - JS_KEY=%v
    volumes:
      - ./nats-%d.conf:/etc/nats/nats-%d.conf:ro
      - ./certs:/certs:ro
      - nats-data-%d:/data
    ports:
      - "%d:%d"
      - "%d:%d"
      - "%d:%d"
    mem_limit: %v
    cpus: %v
    networks: [nats-net]
`, i, i, i, data["JSKey"], i, i, i,
		4222+i, 4222+i, 6222+i, 6222+i, 8222+i, 8222+i,
		data["MemLimit"], data["Cpus"])
	}
	sb.WriteString("networks:\n  nats-net:\nvolumes:\n")
	for i := range replicas {
		fmt.Fprintf(&sb, "  nats-data-%d:\n", i)
	}
	if err := os.WriteFile(filepath.Join(renderDir, "docker-compose.yml"), []byte(sb.String()), 0600); err != nil {
		return err
	}
	return nil
}

// natsAuthBlock renders the users/accounts section from the render data.
func natsAuthBlock(data map[string]any) string {
	appPub, _ := data["AppPublishAllow"].(string)
	appSub, _ := data["AppSubscribeAllow"].(string)
	appHash, _ := data["AppPasswordHash"].(string)
	svcHash, _ := data["SvcPasswordHash"].(string)
	sysHash, _ := data["SysPasswordHash"].(string)
	return fmt.Sprintf(`system_account: SYS
authorization {
  timeout: "2s"
  users: [
    {
      user: "app"
      password: "%s"
      permissions: {
        publish: { allow: %s }
        subscribe: { allow: %s }
      }
    }
    {
      user: "svc"
      password: "%s"
      permissions: {
        publish: {
          allow: ["svc.>"]
          deny: ["svc.secret"]
        }
        subscribe: {
          allow: ["svc.>", "_INBOX.>"]
          deny: ["svc.audit.>"]
        }
      }
    }
  ]
}
accounts {
  SYS: {
    users: [
      { user: "sys", password: "%s" }
    ]
  }
}
`, appHash, appPub, appSub, svcHash, sysHash)
}
