lite:
  ETCD_MEM: 128m
  ETCD_CPUS: "0.25"
  CONTROLLER_MEM: 64m
  CONTROLLER_CPUS: "0.25"
  SQLD_MEM: 256m
  SQLD_CPUS: "0.5"
  ROUTER_MEM: 64m
  ROUTER_CPUS: "0.25"
  REPLICAS: "1"
normal:
  ETCD_MEM: 256m
  ETCD_CPUS: "0.5"
  CONTROLLER_MEM: 128m
  CONTROLLER_CPUS: "0.25"
  SQLD_MEM: 512m
  SQLD_CPUS: "1"
  ROUTER_MEM: 128m
  ROUTER_CPUS: "0.25"
  REPLICAS: "2"
medium:
  ETCD_MEM: 512m
  ETCD_CPUS: "0.5"
  CONTROLLER_MEM: 256m
  CONTROLLER_CPUS: "0.5"
  SQLD_MEM: 1g
  SQLD_CPUS: "2"
  ROUTER_MEM: 256m
  ROUTER_CPUS: "0.5"
  REPLICAS: "2"
large:
  ETCD_MEM: 1g
  ETCD_CPUS: "1"
  CONTROLLER_MEM: 512m
  CONTROLLER_CPUS: "0.5"
  SQLD_MEM: 2g
  SQLD_CPUS: "4"
  ROUTER_MEM: 512m
  ROUTER_CPUS: "1"
  REPLICAS: "3"
